# Simple Azure Pipeline to echo "HELLO WORLD"
trigger:
  branches:
    include:
      - main  # Pipeline triggers when changes are made to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Using Ubuntu as the build agent

steps:
# Display "HELLO WORLD" message
- script: echo "HELLO WORLD"
  displayName: 'Print HELLO WORLD'
